IF OBJECT_ID('Studied', 'U') IS NOT NULL DROP TABLE Studied;
IF OBJECT_ID('Studies', 'U') IS NOT NULL DROP TABLE Studies;
IF OBJECT_ID('Student', 'U') IS NOT NULL DROP TABLE Student;
IF OBJECT_ID('Course', 'U') IS NOT NULL DROP TABLE Course;

CREATE TABLE Student (
  id VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  CONSTRAINT STUDENT_PK_ID PRIMARY KEY(id));
 
CREATE TABLE Course (
  code VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  points int,
  CONSTRAINT COURSE_PK_CODE PRIMARY KEY(code));
 
CREATE TABLE Studies (
  course VARCHAR (255) NOT NULL,
  student VARCHAR (255) NOT NULL,
  semester VARCHAR (255) NOT NULL,
  PRIMARY KEY(course, student),
  CONSTRAINT STUDIES_FK_COURSE FOREIGN KEY(course) REFERENCES Course(code),
  CONSTRAINT STUDIES_FK_STUDENT FOREIGN KEY(student) REFERENCES Student(id));
 
CREATE TABLE Studied (
  course VARCHAR (255) NOT NULL,
  student VARCHAR (255) NOT NULL,
  semester VARCHAR (255) NOT NULL,
  PRIMARY KEY (course, student),
  grade VARCHAR (255),
  CONSTRAINT STUDIED_FK_COURSE FOREIGN KEY(course) REFERENCES Course(code),
  CONSTRAINT STUDIED_FK_STUDENT FOREIGN KEY(student) REFERENCES Student(id));